server:
  port: 8080
spring:
  datasource:
    username: root
    password: coding
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.234.127:1234/auth_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      # ?? 800
      max-lifetime: 43200
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.coding.auth.model
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

